Making the bundler audit check just output warning rather than failing the build.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -64,7 +64,11 @@ jobs:
       # Security analysis
       - run:
           name: Bundler Audit
-          command: bundle exec bundle-audit update && bundle exec bundle-audit check
+          command: |
+            if ! (bundle exec bundle-audit update && bundle exec bundle-audit check); then
+              echo "WARNING: The bundler audit check failed, but we are continuing the build."
+            fi
+
       - run:
           name: Brakeman
           command: ./bin/brakeman
